In [4]:
# the beginning of matricies workings
import random 
import numpy as np
import matplotlib.pyplot as plt
import time
import geopandas as gpd
import pandas as pd
import os

# creation of a matrix that will be used to make random numbers 
# matrix = np.random.rand(3,3)
# print(matrix)

test = np.array([[1,2,3],[4,6,7],[8,9,10]])
print(test)
print(test[0,2] + test[1,2]+ test[2,2])
print("just print out the first array", test[0])

[[ 1  2  3]
 [ 4  6  7]
 [ 8  9 10]]
20
just print out the first array [1 2 3]
