In [10]:
# the beginning of matricies workings
import random 
import numpy as np
import matplotlib.pyplot as plt
import time
import geopandas as gpd
import pandas as pd
import os


In [11]:


# creation of a matrix that will be used to make random numbers 
# matrix = np.random.rand(3,3)
# print(matrix)

test = np.array([[1,2,3],[4,6,7],[8,9,10]])
print(test)
print(test[0,2] + test[1,2]+ test[2,2])
print("just print out the first array", test[0])

[[ 1  2  3]
 [ 4  6  7]
 [ 8  9 10]]
20
just print out the first array [1 2 3]


In [14]:
#random array integers 
for i in range(5):
    #random_array = np.random.sample(0,65, size=(4,5)) 
    random_array = np.random.permutation(65)[:10]
    print(random_array)


[22 46 58 34 48 39  6  7 54 18]
[39 55 60 31 21  3 33  2 35 34]
[32  4 60 14 34 56 10 55 21 30]
[45 31  9  5 51 43 52 56  7 32]
[11  0 54 42 17 26  6 34 47 21]


In [ ]:
# Return a randomized "range" using a Linear Congruential Generator
# to produce the number sequence. Parameters are the same as for 
# python builtin "range".
#   Memory  -- storage for 8 integers, regardless of parameters.
#   Compute -- at most 2*"maximum" steps required to generate sequence.
#
def random_range(start, stop=None, step=None):
    import random, math
    # Set a default values the same way "range" does.
    if (stop == None): start, stop = 0, start
    if (step == None): step = 1
    # Use a mapping to convert a standard range into the desired range.
    mapping = lambda i: (i*step) + start
    # Compute the number of numbers in this range.
    maximum = (stop - start) // step
    # Seed range with a random integer.
    value = random.randint(0,maximum)
    # 
    # Construct an offset, multiplier, and modulus for a linear
    # congruential generator. These generators are cyclic and
    # non-repeating when they maintain the properties:
    # 
    #   1) "modulus" and "offset" are relatively prime.
    #   2) ["multiplier" - 1] is divisible by all prime factors of "modulus".
    #   3) ["multiplier" - 1] is divisible by 4 if "modulus" is divisible by 4.
    # 
    offset = random.randint(0,maximum) * 2 + 1      # Pick a random odd-valued offset.
    multiplier = 4*(maximum//4) + 1                 # Pick a multiplier 1 greater than a multiple of 4.
    modulus = int(2**math.ceil(math.log2(maximum))) # Pick a modulus just big enough to generate all numbers (power of 2).
    # Track how many random numbers have been returned.
    found = 0
    while found < maximum:
        # If this is a valid value, yield it in generator fashion.
        if value < maximum:
            found += 1
            yield mapping(value)
        # Calculate the next value in the sequence.
        value = (value*multiplier + offset) % modulus